<?php

return [
    '2fa'      => 'two factor authentication',
    'verify'   => 'verify',
    'activate' => 'activate 2 factor authentication',
    'code'     => 'Authenticationcode',
    'messages' => [
        'incorrect'       => 'The authentication code is incorrect.',
        'please-verify'   => 'Please verify your changes.',
        'protected'       => 'Your account is protected by two factor authentication',
        'info'            => 'With two-factor authentication, only you can access your account - even if someone else has your password. <a href="https://www.youtube.com/watch?v=0mvCeNsTa1g" target="_blank">Learn more.</a>',
        'how-it-works'    => 'HOW IT WORKS',
        'when-logging-in' => 'When you log in, you must:',
        'step-1'          => 'enter your password',
        'step-2'          => 'enter a code generated by an app',
        'activate'        => [
            'install-app'      => 'Please install an authentication app, e.g:',
            'scan-qr'          => 'Open the Authenticator app on your mobile device and scan the QR Code.',
            'key'              => 'You cannot scan the QR Code? <br />Configure your app with this key:',
            'enter-password'   => 'Enter the password you currently use to log in.',
            'current-password' => 'Current Passwort',
            'step-1'           => 'INSTALL AUTHENTICATOR-APP',
            'step-2'           => 'CONFIGURE APP',
            'step-3'           => 'ENTER YOUR CURRENT PASSWORD',
            'step-4'           => 'ENTER THE SIX-DIGIT CODE GENERATED BY THE APP',
        ],
    ],
];
